### ISSUE TITLE
Can't differentiate based on type of name in SyntaxHighlighter

### ISSUE THREAD

**Issue by Gregoor** [Gregoor/graphql-intellij-plugin#1]
The [SyntaxHighlighter](https://github.com/Gregoor/graphql-intellij-plugin/blob/master/src/graphql/GraphQLSyntaxHighlighter.java) needs to highlight fragment_name differently than field_name. Since they all resolve to ID they have the same elementType.

If I just leave out the rule resolving the *_name's to ID's the whole grammar is broken. That might point to a general underlying error, but I don't know where it would be.

This is my grammar:
https://github.com/Gregoor/graphql-intellij-plugin/blob/master/src/graphql/GraphQL.bnf

**Comment by breandan** [comment]
Hi Gregor, after reading the [GraphQL examples](https://github.com/facebook/graphql), it looks like you could technically differentiate between fragments and fields with [the lexer](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/syntax_highlighting_and_error_highlighting.html#lexer) and `SyntaxHighlighter`, as fragments are always prefixed by `...` or `fragment`, but it would be awkward to write. A better way would be to use [Annotator](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/syntax_highlighting_and_error_highlighting.html#annotator) to do this, since by that point, the grammar is already parsed for you. The lexer is usually just for highlighting keywords, tokens, and so forth, not for distinguishing between higher level constructs, so using `SyntaxHighlighter` in this case is less appropriate.

**Comment by Gregoor** [comment]
Hi Breandan,
thanks for reply! Annotator sounds perfect, I wonder how I managed to skip it.
I thought that I didn't need to add the Lexer because it is generated from my grammar, but I just pushed it.

**Comment by Gregoor** [comment]
Yay, got it to work.
https://github.com/Gregoor/graphql-intellij-plugin/blob/HEAD/src/graphql/GraphQLAnnotator.java

Thanks a lot, I will certainly sleep better tonight! Now I only have to figure out how to make it work with the ColorSettings.

**Comment by breandan** [comment]
Awesome, I'm glad to hear you got it working.

> I thought that I didn't need to add the Lexer because it is generated from my grammar.

The `.flex` file translated from your BNF by GrammarKit via "Generate JFlex lexer" can only generate very simple lexers (but you can use that as a starting point to recognize more complicated state-based lexemes). For an introduction, try reading [Implementing a Lexer](http://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/implementing_lexer.html), and [Lexer and Parser Definition](http://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support/lexer_and_parser_definition.html) in the tutorials.  

Let me know if you have any other issues, it helps to have feedback where developers are getting hung up, so we can document these topics more clearly.

**Comment by Gregoor** [comment]
thanks again, will read it!
So far very happy with the docs, sometimes I have to check github for other projects to find out what has to go in the `plugin.xml`, so having this information in the corresponding chapter might be helpful (though I just noticed that IntelliJ also does a great job telling me what elements are available in the `<lang.*`-namespace).

Edit: If I were to have more questions, where should I preferably ask them? I tried the IntelliJ forum before, but I had less success there.

**Comment by breandan** [comment]
You're right, we need to document the lang [extension points](https://upsource.jetbrains.com/idea-community/file/c8254595ba95ed80eb49e1d1554eb482e496dd04/platform%2Fplatform-resources%2Fsrc%2FMETA-INF%2FLangExtensionPoints.xml?nav=0:0:focused) more carefully. It's on our to-do list.

> Edit: If I were to have more questions, where should I preferably ask them? I tried the IntelliJ forum before, but I had less success there.

Both the [Plugin Development Forum](https://devnet.jetbrains.com/community/idea/open_api_and_plugin_development) and [StackOverflow](http://stackoverflow.com/questions/tagged/intellij-plugin) are good places to ask questions. If you aren't getting answers, please mention one of us on GitHub or Twitter and we'll do our best to respond in a timely manner.
